### ISSUE TITLE
Cannot read property 'dynamicName' of null

### ISSUE THREAD

**Issue by fverloop** [koenbok/monobase#11]
I consistently get these erros when using `Dynamic()`:
![image](https://user-images.githubusercontent.com/1180195/36894902-46a3f11e-1e0d-11e8-98d1-0a6fcbf01f06.png)

Interactiveness of dynamic components is flakey too. Sometimes they work, but most of the times they don't.

**Comment by koenbok** [comment]
Should be fixed now.
