### ISSUE TITLE
Console.log’s are swallowed

### ISSUE THREAD

**Issue by koenbok** [koenbok/monobase#3]
Okay this is definitely not the case, but it's confusing as:

1) Every console.log statement ends up in the terminal console.
2) _Only dynamic_ components console.log end up in the browser inspector console.

![](https://cl.ly/151Y3Y0h333U/Screen%20Recording%202018-01-12%20at%2002.03%20PM.gif)

**Comment by fverloop** [comment]
Yes, this all makes sense now.
