### ISSUE TITLE
Component Styling

### ISSUE THREAD

**Issue by koenbok** [koenbok/monobase#4]
**Styled Components**

- Would love to use Styled Components. It’s great for setting up complete style libraries like we’re currently using for framer.com. It also has full support for media queeries, which is important for responsiveness.
- Currently installing a new package breaks monobase. I need to remove `node_modules` and `package-lock.json` and reinstall. (might be my local npm version being funky)
- When Styled components _is_ installed, it’s not working. 
- The way it should work: 
    - 1. Adds unique classnames to element
    - 2. Adds style tag to head with styling for specific element
- Out of the box it currently only adds a unique class name to an element. 
- When exporting a styled component using the Dynamic function, it adds a unique class name to the element and a style tag to the head. Unfortunately the style tag is empty.
- Maybe we could use something like react-helmet to dynamically edit the `<head/>` (edited)

**Comment by koenbok** [comment]
I looked into both Styled Components and styled-jsx and I think they're both bad options (in this case). I'll elaborate:

### Styled Components

- The setup can only be done at template / top level, as the resulting stylesheet has to be injected in the head to really make sense.
- Ideally it should be a kind of combined style sheet for the entire site, but instead we'll have one for each page with quite some overlap.
- The setup as long string will completely defaut the purpose of TypeScript with autocomplete and React property checking, allowing for way more bugs to slip in.

### Styled-JSX

I think most of the other things stay true, but the syntax is better with jsx addons. Unfortunately we don't use Babel but TypeScripts built-in jsx processor.

**Comment by koenbok** [comment]
Why wouldn't we use a central typed css.ts file like this:

```ts
interface CSSCollection {
    [key: string]: React.CSSProperties
}

export const padding: CSSCollection = {
  small: { padding: 100 },
  large: { padding: 200 }
}
```

And then we can use inline styles like this

**Comment by koenbok** [comment]
I added an example to the default template.

**Comment by fverloop** [comment]
Ah too bad! Styled-components would've given us a lot of powerful tools out of the box. Mainly theming and responsive styling. It's also widely supported and actively maintained. 

It's nothing we can't fix ourselves though. Plus, having typed CSS and full control is nice. I'll give your setup a try.

**Comment by koenbok** [comment]
Related: https://twitter.com/dan_abramov/status/953275668640432128

**Comment by fverloop** [comment]
Alright, I've been playing around with it and I *really* like the idea of a strongly typed CSS setup. It removes a lot of room for error and allows us to fully document the API, making it easy to write CSS for everyone.

I'm trying to get a feel for how we could leverage CSS and TypeScript to provide a really nice (restricted) API for writing CSS. Below are a couple of explorations, I would love some feedback on this.

## Example: Scales
We'll use a set scale of 6 units. The values of are different based on context. For padding, we'd use a more aggressive scale compared to for example font size. We need flexibility for this.

#### Option 1: Array based
``` Typescript

// OPTION 1: Array based

/** Fixed Scale with 6 units */
type CSSScale<T> = [T, T, T, T, T, T]

/** Size helper */
enum Size {
  xxs,
  xs,
  s,
  m,
  l,
  xl
}

/** Sets all round padding */
const padding: CSSScale<{padding: React.CSSLength}> = [
  {padding: "5px"},
  {padding: "10px"},
  {padding: "20px"},
  {padding: "40px"},
  {padding: "80px"},
  {padding: "120px"}
]

/** Sets font size to: */
const fontSize: CSSScale<{fontSize: React.CSSLength}> = [
  {fontSize: "14px"},
  {fontSize: "18px"},
  {fontSize: "22px"},
  {fontSize: "32px"},
  {fontSize: "46px"},
  {fontSize: "72px"},
  {fontSize: "120px"}
]

// RESULT

// With Size helper
padding[Size.m]

// OR
padding[3]

// Downsides: 
// - it's weird to have padding[0] as a scale option.
// - No nice documentation for values
```

#### Option 2: Object based
``` TypeScript
interface PaddingScale {
  /** Value: 5px */
  xxs: React.CSSLength
  /** Value: 10px */
  xs: React.CSSLength
  /** Value: 20px */
  s: React.CSSLength
  /** Value: 40px */
  m: React.CSSLength
  /** Value: 80px */
  l: React.CSSLength
  /** Value: 120px */
  xl: React.CSSLength
}

/** Sets all round padding */
const padding: PaddingScale = {
  xxs: "14px",
  xs: "18px",
  s: "20px",
  m: "40px",
  l: "80px",
  xl: "120px"
}

// RESULT
padding.s
```

Option 2 works really nice wit Intellisense:
![screen recording code](https://user-images.githubusercontent.com/1180195/35014693-eb5557bc-fb11-11e7-9f49-b312e048da1d.gif)

## Example: Color
A set palette of brand colors.

#### Option 1: Object based
``` TypeScript
interface Palette<T> {
  /** Standard Framer blue */
  blue: T

  /** Darkest Framer blue */
  blueDeep: T

  /** Lightest Framer blue */
  blueBaby: T

  /** Used for warnings */
  red: T
}

const Color: Palette<string> = {
  blue: "#0AF",
  blueDeep: "#05F",
  blueBaby: "#0AF",
  red: "#F44"
}

const background: Palette<{backgroundColor: string}> = {
  blueDeep: {backgroundColor: Color.blueDeep},
  blue: {backgroundColor: Color.blue},
  blueBaby: {backgroundColor: Color.blueBaby},
  red: {backgroundColor: Color.red}
}

const fontColor: Palette<{color: string}> = {
  blueDeep: {color: Color.blueDeep},
  blue: {color: Color.blue},
  blueBaby: {color: Color.blueBaby},
  red: {color: Color.red}
}

// RESULT
background.red
```

#### Option 2: Function based
```Typescript
interface Palette<T> {
  /** Standard Framer blue */
  blue: T

  /** Darkest Framer blue */
  blueDeep: T

  /** Lightest Framer blue */
  blueBaby: T

  /** Used for warnings */
  red: T
}

type colorType = "#0AF" | "#05F" | "#0AF" | "#F44"
const Color: Palette<colorType> = {
  blue: "#0AF",
  blueDeep: "#05F",
  blueBaby: "#0AF",
  red: "#F44"
}

// RESULT
const background = (color: colorType) => ({
  backgroundColor: color
})

const fontColor = (color: colorType) => ({
  color
})
```

**Comment by koenbok** [comment]
An additional advantage of using css in JavaScript is tree-shaking; only the actually used code (so css) gets shipped in the final bundle.

A downside of setting everything on the elements is that you may get some duplicate css, but I'm pretty sure gzip compression will offset most of this.

A benefit of setting style on the elements is that you won't have global scoping issues.

**Comment by jaredpalmer** [comment]
@koenbok You can use glamor and typescript fairly easily with this trick: 

https://github.com/threepointone/glamor/issues/283

**Comment by fverloop** [comment]
@koenbok I think we need to _at least_ offer support for:
- Vendor prefixes / fallback values
- All the pseudo :classes/::elements
- @media queries
- @supports statements
- @font-face / @keyframes

As @jaredpalmer stated, Glamor seems to be a good option for that, since it works nicely with TypeScript.

**Comment by felixhageloh** [comment]
came across this while researching our next styling solution (hi @koenbok, it's been a while).

We've been using inline styles with a central styles file/module for a while now (in plain JS so no types). It works quite well, but the lack of pseudo classes is a big one: Hover styles become a big pain because you need to implement them in JS using mouse events. 

We are now looking into combining the current solution with Glamor. It seems to have all advantage of inline styles with the addition of supporting pseudo classes, media queries etc. You also don't have to worry about the size of your HTML anymore (we are not doing SSR yet, so it was no issue for us). 

The only open question for me is how to do styling of child components. I think in general, components should define their own _style_, but it would be very handy to have components be able to control the _layout_ of their children. For example, you would like a form component control the padding and sizing of form fields, without having to explicitly set it for every form you implement.

**Comment by koenbok** [comment]
@jaredpalmer we ended up using a thin layer on top of glamor, plus your suggestion! I'll put it in a separate little library.

**Comment by koenbok** [comment]
Here we go: https://github.com/koenbok/stijl
