### ISSUE TITLE
Smarter routing

### ISSUE THREAD

**Issue by fverloop** [koenbok/monobase#7]
Could we make monobase automatically set-up routes based on the `/pages` folder structure?

| Location | Route |
|:--|:--|
| /pages/index.ts | /index |
| /pages/features.ts | /features |
| /pages/features/index.ts | /features |
| /pages/features/design.ts | /features/design |
| /pages/features/design/index.ts | /features/design |

**Comment by koenbok** [comment]
This is in there.
