### ISSUE TITLE
Default project structure

### ISSUE THREAD

**Issue by fverloop** [koenbok/monobase#8]
Playing around with the project structure. How about this?

- **components**
  - dynamic *— interactive components*
  - static *— non-interactive components*
- **pages** *— folder structure defines routes*
- **templates** *— all components receive: path, context and config*
- **static**
  - images
  - fonts
- **theme** *— basic setup for typed styling*

**Comment by benjamindenboer** [comment]
Having two folders named "static" could be a source of confusion, though.

**Comment by benjamindenboer** [comment]
I don’t think we have to be explicit in differentiating static and dynamic components.

**Comment by fverloop** [comment]
We _have_ to because monobase needs to know which components are dynamic. Koen found another solution though!

**Comment by koenbok** [comment]
We discover dynamic components with `Dynamic()`
